---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

params:
  IAAS:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  PKS_SINGLETON_JOB_AZ:
  PKS_NW_AZS:
  PKS_DEPLOYMENT_NETWORK_NAME:
  PKS_CLUSTER_SERVICE_NETWORK_NAME:
  PKS_SSL_CERT:
  PKS_SSL_PRIVATE_KEY:
  PKS_SYSTEM_DOMAIN:
  PKS_UAA_DOMAIN_PREFIX:
  PKS_VCENTER_HOST:
  PKS_VCENTER_USR:
  PKS_VCENTER_PWD:
  PKS_VCENTER_DATA_CENTER:
  PKS_VCENTER_DATASTORE:
  PKS_VCENTER_CLUSTER:
  PKS_VM_FOLDER:
  PKS_CLI_USER:
  PKS_CLI_PASSWORD:
  PKS_CLI_EMAIL:
  PKS_PLAN_DETAILS:
  PKS_VCENTER_CLUSTER_LIST:
  PKS_SYSLOG_ADDRESS:
  PKS_SYSLOG_PORT:
  PKS_SYSLOG_TRANSPORT_PROTOCOL:
  PKS_SYSLOG_TLS_ENABLED:
  PKS_SYSLOG_PEER:
  PKS_SYSLOG_CA_CERT:
  PKS_SYSLOG_MIGRATION_ENABLED:
  PKS_ALLOW_PUBLIC_IP:
  PKS_ENABLE_HTTP_PROXY:
  PKS_HTTP_PROXY_URL:
  PKS_HTTP_PROXY_USER:
  PKS_HTTP_PROXY_PASSWORD:
  PKS_HTTPS_PROXY_URL:
  PKS_HTTPS_PROXY_USER:
  PKS_HTTPS_PROXY_PASSWORD:
  PKS_NO_PROXY:
  PKS_UAA_USE_LDAP:
  PKS_LDAP_URL:
  PKS_LDAP_USER:
  PKS_LDAP_PASSWORD:
  PKS_LDAP_SEARCH_BASE:
  PKS_LDAP_GROUP_SEARCH_BASE:
  PKS_LDAP_SERVER_SSL_CERT:
  PKS_LDAP_SERVER_SSL_CERT_ALIAS:
  PKS_LDAP_EMAIL_DOMAINS:
  PKS_LDAP_FIRST_NAME_ATTRIBUTE:
  PKS_LDAP_LAST_NAME_ATTRIBUTE:
  PKS_TELEMETRY:
  PKS_DISABLE_NSX_T_PRECHECK_ERRAND:

inputs:
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/config-pks/task-no-nsx.sh
